CC = g++
FLAGS = -std=c++17 -Wall -g  # wall says show errors, g says create a debug mode
OBJS = cardDeckClass.o 

all: hw02

hw02: hw02.cpp cardDeckClass.o   # step 2 build program
	$(CC) $(FLAGS) hw02.cpp -o hw02 $(OBJS)

cardDeckClass.o: cardDeckClass.h
	$(CC) $(FLAGS) -c cardDeckClass.cpp -o cardDeckClass.o

clean:
	rm -f *.o hw02 hw02.tar

tar:
	tar cf hw02.tar hw02.scr Makefile hw02.cpp cardDeckClass.h cardDeckClass.cpp 